# Generated by Django 2.0.5 on 2019-03-07 17:36

import blogs.models
from django.conf import settings
from django.db import migrations, models
import taxonomies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxonomies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(blogs.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='文章作者'),
        ),
        migrations.AddField(
            model_name='album',
            name='category1',
            field=models.ForeignKey(on_delete=models.SET(taxonomies.models.get_sentinel_category1), to='taxonomies.FirstCategory', verbose_name='一级类别'),
        ),
        migrations.AddField(
            model_name='album',
            name='category2',
            field=models.ForeignKey(on_delete=models.SET(taxonomies.models.get_sentinel_category2), to='taxonomies.SecondCategory', verbose_name='二级类别'),
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, to='taxonomies.Tag', verbose_name='文集标签'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(blogs.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='文集作者'),
        ),
    ]
