# Generated by Django 2.0.5 on 2019-03-10 16:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0002_auto_20190307_1736'),
        ('operations', '0002_auto_20190307_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumFavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Album', verbose_name='专辑')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '专辑收藏',
                'verbose_name_plural': '专辑收藏',
            },
        ),
        migrations.AlterUniqueTogether(
            name='albumfavor',
            unique_together={('user', 'album')},
        ),
    ]
